dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: express-hello
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: hello-4-2
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: hello-4-3
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: hello-4-4
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: hello-video-3-1
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: spring-boot-http-gradle
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
